name: harvester
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22
  - cloudpickle==2.0.0
  - fsspec
  - s3fs
  - dask
  - loguru
  - pandas
  - progressbar2
  - typer
  - zarr
  - xarray
  - lxml
  - gspread
  - fastparquet
  - pygithub
  - siphon
  - prefect<2
  - requests-html
  - rechunker
  - flatten-dict
  - pip:
      - git+https://github.com/ooi-data/ooi-harvester.git@main
