name: meta_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - fsspec
  - requests
  - s3fs
  - dask
  - loguru
  - pandas
  - progressbar2
  - typer
  - zarr
  - xarray
  - lxml
  - gspread
  - google-auth-oauthlib=0.5.3
  - fastparquet
  - pygithub
  - siphon
  - prefect
  - rechunker
  - pip:
    - git+https://github.com/pangeo-forge/pangeo-forge.git@0.1.0
